### ISSUE TITLE
Suggestion: Video embeds should be playable in Discord

### ISSUE THREAD

**Issue by Shamunr** [cirroskais/embedsky#1]
When embedding a video it gives a thumbnail but still cannot be played from within discord.  Any way to get that to be embedded as a playable video in Discord?

**Comment by cirroskais** [comment]
There is a way to do this, and this is something I have planned. It requires using ffmpeg to "buffer" the playlist that Bluesky serves since Discord does not load .m3u8 files. Discord also hides the description field on video embeds, so a different field will need to be used. Possibly the provider field from oEmbed, which is the popular option. I'll get to work on this.
